name: Test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
        pnpm-version: [8.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: pnpm install
        
      - name: Transpile code
        run: pnpm transpile
        
      - name: Test and generate coverage report
        run: pnpm cover:generate
      
      - name: Send coverage report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v3
        